apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script
  namespace: vault
data:
  startup.sh: |
    #!/bin/sh

    sleep 5

    initialized=$(vault status | grep -i initialized | awk '{print $2}')
    unseal_file="/vault/data/unseal-keys.txt"

    if [ "$initialized" != "true" ]; then
        echo "Vault not initialized. Initializing Vault"
        vault operator init > $unseal_file
    fi

    threshold=$(vault status | grep -i threshold | awk '{print $2}')

    count=1
    while [ $count -le $threshold ]
    do
        key=$(cat $unseal_file | grep -i "Unseal Key ${count}" | awk '{print $4}') 
        vault operator unseal $key
        count=$((count + 1))
    done

    echo "done"