global:
  enabled: true

injector:
  enabled: false 

server:
  logLevel: info
  logFormat: standard
  dataStorage: 
    size: 5Gi 
  httproute:
    enabled: true
    activeService: true
    hostnames: 
      - vault.example.com
    parentRefs: 
      - group: gateway.networking.k8s.io	
        kind: Gateway 
        name: traefik
        namespace: traefik 
    rules:
      - backendRefs:
        - group: ""
          kind: Service
          name: vault
          port: 8200
          weight: 1
    matches:
      - path:
          type: PathPrefix
          value: /

  standalone:
    enabled: true 

ui:
  enabled: true