nameOverride: argocd

global:
  domain: argocd.example.com
  revisionHistoryLimit: 1

  image:
    tag: v3.5.2

  logging:
    format: json

# TODO: Add OIDC config using Keycloak, once Keycloak is deployed. Add policies and roles
configs:
  params: 
    server.insecure: true
  # General Argo CD configuration. Any values you put under `.configs.cm` are passed to argocd-cm ConfigMap.
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    # -- Create the argocd-cm configmap for [declarative setup]
    create: true

    # OIDC configuration as an alternative to dex (optional).
    # oidc.config: |
    #   name: AzureAD
    #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
    #   clientID: aaaabbbbccccddddeee
    #   clientSecret: $oidc.azuread.clientSecret
    #   # Optional: set to true to use Azure Workload Identity instead of clientSecret
    #   azure:
    #     useWorkloadIdentity: false

    
    # Optional list of allowed aud claims. If omitted or empty, defaults to the clientID value above (and the
    # cliClientID, if that is also specified). If you specify a list and want the clientID to be allowed, you must
    # explicitly include it in the list.
    # Token verification will pass if any of the token's audiences matches any of the audiences in this list.
    #   allowedAudiences:
    #     - aaaabbbbccccddddeee
    #     - qqqqwwwweeeerrrrttt

    # Optional set of OIDC claims to request on the ID token.
    #   requestedIDTokenClaims:
    #     groups:
    #       essential: true

    # Optional set of OIDC scopes to request. If omitted, defaults to: ["openid", "profile", "email", "groups"]
    #   requestedScopes:
    #     - openid
    #     - profile
    #     - email

  # Argo CD RBAC policy configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
  rbac:
    # -- Create the argocd-rbac-cm configmap with ([Argo CD RBAC policy]) definitions.
    # If false, it is expected the configmap will be created by something else.
    # Argo CD will not work if there is no configmap created with the name above.
    create: true

    # -- Annotations to be added to argocd-rbac-cm configmap
    annotations: {}

    # -- The name of the default role which Argo CD will falls back to, when authorizing API requests (optional).
    # If omitted or empty, users may be still be able to login, but will see no apps, projects, etc...
    policy.default: ""

    # -- File containing user-defined policies and role definitions.
    # @default -- `''` (See [values.yaml])
    policy.csv: ""
    # Policy rules are in the form:
    #  p, subject, resource, action, object, effect
    # Role definitions and bindings are in the form:
    #  g, subject, inherited-subject
    # policy.csv: |
    #   p, role:org-admin, applications, *, */*, allow
    #   p, role:org-admin, clusters, get, *, allow
    #   p, role:org-admin, repositories, *, *, allow
    #   p, role:org-admin, logs, get, *, allow
    #   p, role:org-admin, exec, create, */*, allow
    #   g, your-github-org:your-team, role:org-admin

    # -- OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
    # The scope value can be a string, or a list of strings.
    scopes: "[groups]"

    # -- Matcher function for Casbin, `glob` for glob matcher and `regex` for regex matcher.
    policy.matchMode: "glob"

  tls:
    create: false

  secret:
    createSecret: true

dex:
  enabled: false

server:
  httproute:
    enabled: true
    parentRefs: 
      - name: traefik
        namespace: traefik
    hostnames: 
      - argocd.example.com
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

notifications:
  enabled: false
