AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    web_replicas: 1
    task_replicas: 1
    postgres_security_context_settings:
      fsGroup: 26
    postgres_data_volume_init: true
    postgres_init_container_commands: |
      chown 26:0 /var/lib/pgsql/data
      chmod 700 /var/lib/pgsql/data

rbac:
  create: true

operator-controller:
  spec: 
    replicas: 1