apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx 
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: awx-operator 
      repoURL: https://ansible-community.github.io/awx-operator-helm/
      targetRevision: 3.2.1
      helm:
        releaseName: awx 
        valueFiles: 
          - $values/helm/system/awx.yml
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      path: config/system/awx
      directory: 
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  ignoreDifferences: 
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: awx-httproute
      jqPathExpressions:
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
        - .spec.rules[].backendRefs[].group
        - .spec.rules[].backendRefs[].kind
        - .spec.rules[].backendRefs[].weight

  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - ServerSideApply=true