apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager 
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io 
      targetRevision: 1.21.1
      helm:
        releaseName: cert-manager 
        valueFiles: 
          - $values/helm/system/cert-manager.yml
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      path: config/system/cert-manager
      directory: 
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager  
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - ServerSideApply=true