apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb 
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: metallb 
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.16.1
      helm:
        releaseName: metallb 
        valueFiles: 
          - $values/helm/system/metallb.yml
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      path: config/system/metallb
      directory: 
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true