apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik 
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 41.2.0
      helm:
        releaseName: traefik 
        valueFiles: 
          - $values/helm/system/traefik.yml
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/LokeshMudhalvan/KubernetesCluster.git
      targetRevision: main
      path: config/system/traefik
      directory: 
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true